name: Cypress Tests

on:
  push:
    branches:
      - main  # Executa a pipeline quando houver push na branch main
  pull_request:
    branches:
      - main  # Executa a pipeline em PRs na branch main

jobs:
  cypress-run:
    runs-on: ubuntu-latest  # Sistema operacional usado no runner

    services:
      mysql:
        image: mysql:5.7
        env:
           DB_HOST: ${{ secrets.DB_HOST }}
           DB_USER: ${{ secrets.DB_USER }}
           DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
           DB_NAME: ${{ secrets.DB_NAME }}
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --host=localhost --user=root --password=root"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependências
        run: npm install

      - name: Configurar banco de dados
        run: |
          npm install -g mysql
  
      - name: Rodar testes Cypress
        run: npx cypress run
        env:
           DB_HOST: ${{ secrets.DB_HOST }}
           DB_USER: ${{ secrets.DB_USER }}
           DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
           DB_NAME: ${{ secrets.DB_NAME }}
